/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.geneticAlgorithm.GUI;

import com.geneticAlgorithm.database.MysqlConnect;
import com.geneticAlgorithm.util.util;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author trias
 */
public class FrmDosen extends javax.swing.JInternalFrame {

    private int _selectedkode;

    /**
     * Creates new form FrmDosen
     */
    public FrmDosen() {
        initComponents();

        setButtonStatus(true, false, false);
        try {
            loadData();
        } catch (SQLException ex) {
            Logger.getLogger(FrmDosen.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void loadData() throws SQLException {
        String query
                = "SELECT kode,"
                + "       nidn as NIDN,"
                + "       nama as Nama,"
                + "       alamat as Alamat,"
                + "       telp as Telp "
                + "FROM dosen "
                + "ORDER BY kode";
        ResultSet rs = MysqlConnect.getDbCon().ExecuteQuery(query);
        jTable1.setModel(util.buildTableModel(rs));
    }

    private void setButtonStatus(boolean bBaru, boolean bBatal, boolean bSimpan) {
        btnBaru.setEnabled(bBaru);
        btnBatal.setEnabled(bBatal);
        btnSimpan.setEnabled(bSimpan);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtKode = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNIDN = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtAlamat = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtTelp = new javax.swing.JTextField();
        btnBaru = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setTitle("Form Dosen");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setText("Kode");

        jLabel4.setText("NIDN");

        jLabel5.setText("Nama");

        jLabel6.setText("Alamat");

        jLabel7.setText("Telp");

        btnBaru.setText("Data Baru");
        btnBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBaruActionPerformed(evt);
            }
        });

        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnBaru)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 290, Short.MAX_VALUE)
                        .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtKode, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNIDN, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelp, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtNama, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                        .addComponent(txtAlamat, javax.swing.GroupLayout.Alignment.LEADING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSimpan)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNIDN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBaru)
                    .addComponent(btnBatal)
                    .addComponent(btnSimpan))
                .addContainerGap())
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBaruActionPerformed
        // TODO add your handling code here:
        txtKode.setText("");
        txtNIDN.setText("");
        txtNama.setText("");
        txtAlamat.setText("");
        txtTelp.setText("");

        setButtonStatus(false, true, true);
        _selectedkode = -1;
    }//GEN-LAST:event_btnBaruActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        if (("".equals(txtKode.getText().trim()) || "".equals(txtNIDN.getText().trim()))
                || "".equals(txtNama.getText().trim())) {
            JOptionPane.showMessageDialog(null, "Data Belum Lengkap");
            return;
        } 

        if (_selectedkode != -1) {
            //update data
            String check = String.format(
                    "SELECT CAST(COUNT(*) AS CHAR(1)) "
                    + "FROM dosen "
                    + "WHERE (kode= %d OR nidn= '%s') AND kode <> %d",
                    Integer.parseInt(txtKode.getText()), txtNama.getText(), _selectedkode);
            try {
                int i = Integer.parseInt(MysqlConnect.getDbCon().ExecuteScalar(check));

                if (i != 0) {
                    JOptionPane.showMessageDialog(null, "Kode Atau NIDN ini sudah ada!");
                    return;
                }

                String Qry_update = String.format(
                        "UPDATE dosen "
                        + "SET kode = %d,"
                        + "    nidn = '%s', "
                        + "    nama = '%s', "
                        + "    alamat = '%s', "
                        + "    telp = '%s' "
                        + "WHERE kode = %d",
                        Integer.parseInt(txtKode.getText()),
                        txtNIDN.getText(),
                        txtNama.getText(),
                        txtAlamat.getText(),
                        txtTelp.getText(),
                        _selectedkode
                );
                MysqlConnect.getDbCon().insert(Qry_update);

                //update waktu_tidak_bersedia
                Qry_update = String.format(
                        "UPDATE waktu_tidak_bersedia "
                        + "SET kode_dosen = %d "
                        + "WHERE kode_dosen = %d",
                        Integer.parseInt(txtKode.getText()),
                        _selectedkode
                );
                MysqlConnect.getDbCon().insert(Qry_update);

            } catch (SQLException ex) {
                Logger.getLogger(FrmPengampu.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            //new data
            String check = String.format(
                    "SELECT CAST(COUNT(*) AS CHAR(1)) "
                    + "FROM dosen "
                    + "WHERE (kode= %d OR nidn= '%s')",
                    Integer.parseInt(txtKode.getText()), txtNama.getText());

            try {
                int i = Integer.parseInt(MysqlConnect.getDbCon().ExecuteScalar(check));

                if (i != 0) {
                    JOptionPane.showMessageDialog(null, "Kode Atau NIDN ini sudah ada!");
                    return;
                }

                String Qry_insert = String.format(
                        "INSERT INTO dosen(kode,nidn,nama,alamat,telp) VALUES(%d,'%s','%s','%s','%s')",
                        Integer.parseInt(txtKode.getText()), txtNIDN.getText(),
                        txtNama.getText(), txtAlamat.getText(),
                        txtTelp.getText());
                MysqlConnect.getDbCon().insert(Qry_insert);

            } catch (SQLException ex) {
                Logger.getLogger(FrmPengampu.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

        _selectedkode = -1; //set to "-1" agar disign sebagai databaru
        txtKode.setText("");
        txtNIDN.setText("");
        txtNama.setText("");
        txtAlamat.setText("");
        txtTelp.setText("");

        setButtonStatus(true, false, false);

        try {
            loadData();
        } catch (SQLException ex) {
            Logger.getLogger(FrmPengampu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        setButtonStatus(true, false, false);
        txtKode.setText("");
        txtNIDN.setText("");
        txtNama.setText("");
        txtAlamat.setText("");
        txtTelp.setText("");
    }//GEN-LAST:event_btnBatalActionPerformed

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        // TODO add your handling code here:
        
        int row = jTable1.getSelectedRow();
        
        setButtonStatus(false, true, true);
        _selectedkode = Integer.parseInt(jTable1.getModel().getValueAt(row, 0).toString());
        txtKode.setText(jTable1.getModel().getValueAt(row, 0).toString());
        txtNIDN.setText(jTable1.getModel().getValueAt(row, 1).toString());
        txtNama.setText(jTable1.getModel().getValueAt(row, 2).toString());
        txtAlamat.setText(jTable1.getModel().getValueAt(row, 3).toString());
        txtTelp.setText(jTable1.getModel().getValueAt(row, 4).toString());
    }//GEN-LAST:event_jTable1MousePressed

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
                
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_DELETE) {

            if (JOptionPane.showConfirmDialog(null, "Yakin ingin menghapus data ini?",
                    "Konfirmasi",
                    JOptionPane.YES_NO_OPTION) != JOptionPane.YES_OPTION) {
                return;
            }

            int row = jTable1.getSelectedRow();
            _selectedkode = Integer.parseInt(jTable1.getModel().getValueAt(row, 0).toString());
            
            String Qry_Delete = "DELETE FROM dosen where kode =  " + _selectedkode;
            try {
                MysqlConnect.getDbCon().ExecuteNonQuery(Qry_Delete);
            } catch (SQLException ex) {
                Logger.getLogger(FrmPengampu.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            Qry_Delete = "DELETE FROM pengampu where kode_dosen =  " + _selectedkode;
            try {
                MysqlConnect.getDbCon().ExecuteNonQuery(Qry_Delete);
            } catch (SQLException ex) {
                Logger.getLogger(FrmPengampu.class.getName()).log(Level.SEVERE, null, ex);
            }

            _selectedkode = -1;
            setButtonStatus(true, false, false);
            try {
                loadData();
            } catch (SQLException ex) {
                Logger.getLogger(FrmPengampu.class.getName()).log(Level.SEVERE, null, ex);
            }
        } 
    }//GEN-LAST:event_jTable1KeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBaru;
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtKode;
    private javax.swing.JTextField txtNIDN;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtTelp;
    // End of variables declaration//GEN-END:variables
}
