/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.geneticAlgorithm.GUI;

import com.geneticAlgorithm.database.MysqlConnect;
import com.geneticAlgorithm.util.util;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author trias
 */
public class FrmJam extends javax.swing.JInternalFrame {

    private int _selectedkode;
    
    /**
     * Creates new form FrmJam
     */
    public FrmJam() {
        initComponents();
        
        setButtonStatus(true, false, false);
        try {
            loadData();
        } catch (SQLException ex) {
            Logger.getLogger(FrmDosen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

     private void loadData() throws SQLException {
        String query
                = "SELECT * FROM jam";
        ResultSet rs = MysqlConnect.getDbCon().ExecuteQuery(query);
        jTable1.setModel(util.buildTableModel(rs));
        jTable1.removeColumn(jTable1.getColumnModel().getColumn(2));
    }
     
    private void setButtonStatus(boolean bBaru, boolean bBatal, boolean bSimpan) {
        btnBaru.setEnabled(bBaru);
        btnBatal.setEnabled(bBatal);
        btnSimpan.setEnabled(bSimpan);
    }
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtKode = new javax.swing.JTextField();
        txtRange = new javax.swing.JTextField();
        btnBaru = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setTitle("Form Jam");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Jam Ke");

        jLabel2.setText("Range");

        btnBaru.setText("Data Baru");
        btnBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBaruActionPerformed(evt);
            }
        });

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnBaru)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtRange, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtKode, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(92, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtRange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBaru)
                    .addComponent(btnSimpan)
                    .addComponent(btnBatal))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed

        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_DELETE) {

            if (JOptionPane.showConfirmDialog(null, "Yakin ingin menghapus data ini?",
                    "Konfirmasi",
                    JOptionPane.YES_NO_OPTION) != JOptionPane.YES_OPTION) {
                return;
            }

            int row = jTable1.getSelectedRow();
            _selectedkode = Integer.parseInt(jTable1.getModel().getValueAt(row, 0).toString());

            String Qry_Delete = "DELETE FROM jam where kode =  " + _selectedkode;
            try {
                MysqlConnect.getDbCon().ExecuteNonQuery(Qry_Delete);
            } catch (SQLException ex) {
                Logger.getLogger(FrmPengampu.class.getName()).log(Level.SEVERE, null, ex);
            }

            _selectedkode = -1;
            setButtonStatus(true, false, false);
            try {
                loadData();
            } catch (SQLException ex) {
                Logger.getLogger(FrmPengampu.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jTable1KeyPressed

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        int row = jTable1.getSelectedRow();

        setButtonStatus(false, true, true);
        _selectedkode = Integer.parseInt(jTable1.getModel().getValueAt(row, 0).toString());

        txtKode.setText(jTable1.getModel().getValueAt(row, 0).toString());
        txtRange.setText(jTable1.getModel().getValueAt(row, 1).toString());
    }//GEN-LAST:event_jTable1MousePressed

    private void btnBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBaruActionPerformed
        txtKode.setText("");
        txtRange.setText("");        
        setButtonStatus(false, true, true);
        _selectedkode = -1;
    }//GEN-LAST:event_btnBaruActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        setButtonStatus(true, false, false);
        txtRange.setText("");
        txtKode.setText("");
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
       if ("".equals(txtKode.getText().trim()) || "".equals(txtRange.getText().trim())) {
            JOptionPane.showMessageDialog(null, "Data Belum Lengkap");
            return;
        }

        if (_selectedkode != -1) {
            //update data
            String check = String.format(
                    "SELECT CAST(COUNT(*) AS CHAR(1)) "
                    + "FROM jam "
                    + "WHERE (kode='%s' OR range_jam='%s') AND kode <> %d",
                    txtKode.getText(),txtRange.getText(), _selectedkode);
            try {
                int i = Integer.parseInt(MysqlConnect.getDbCon().ExecuteScalar(check));

                if (i != 0) {
                    JOptionPane.showMessageDialog(null, "Kode atau Range ini sudah ada!");
                    return;
                }

                String Qry_update = String.format(
                        "UPDATE jam "
                        + "set kode = %d, "
                        + "    range_jam = '%s', "
                        + "    aktif = '%s' "        
                        + "where kode = %d",                        
                        Integer.parseInt(txtKode.getText()),
                        txtRange.getText(),  
                        "Y",
                        _selectedkode
                );
                MysqlConnect.getDbCon().insert(Qry_update);

            } catch (SQLException ex) {
                Logger.getLogger(FrmPengampu.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            //new data
            String check = String.format(
                    "SELECT CAST(COUNT(*) AS CHAR(1)) "
                    + "FROM jam "
                    + "WHERE kode = %d OR range_jam= '%s'",
                     Integer.parseInt(txtKode.getText()),
                     txtRange.getText());

            try {
                int i = Integer.parseInt(MysqlConnect.getDbCon().ExecuteScalar(check));

                if (i != 0) {
                    JOptionPane.showMessageDialog(null, "Kode Atau Range ini sudah ada!");
                    return;
                }

                String Qry_insert = String.format(
                        "INSERT INTO jam(kode,range_jam,aktif) VALUES(%d,'%s','%s')",
                        Integer.parseInt(txtKode.getText()), 
                        txtRange.getText(),  
                        "Y");
                MysqlConnect.getDbCon().insert(Qry_insert);

            } catch (SQLException ex) {
                Logger.getLogger(FrmPengampu.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

        _selectedkode = -1; //set to "-1" agar disign sebagai databaru

        txtRange.setText("");
        txtKode.setText("");
        setButtonStatus(true, false, false);

        try {
            loadData();
        } catch (SQLException ex) {
            Logger.getLogger(FrmPengampu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSimpanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBaru;
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtKode;
    private javax.swing.JTextField txtRange;
    // End of variables declaration//GEN-END:variables
}
