/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.geneticAlgorithm.GUI;

import com.geneticAlgorithm.database.MysqlConnect;
import com.geneticAlgorithm.util.util;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author trias
 */
public class FrmMatakuliah extends javax.swing.JInternalFrame {

    private int _selectedkode;

    /**
     * Creates new form FrmMatakuliah
     */
    public FrmMatakuliah() {
        initComponents();
        setButtonStatus(true, false, false);
        try {
            loadData();
        } catch (SQLException ex) {
            Logger.getLogger(FrmDosen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadData() throws SQLException {
        String query = "SELECT kode as id,"
                + "       kode_mk as Kode,"
                + "       nama as Nama,"
                + "       sks as SKS,"
                + "       semester as Semester,"
                + "       jenis as Jenis " + //combobox
                "FROM mata_kuliah ORDER BY nama";
        ResultSet rs = MysqlConnect.getDbCon().ExecuteQuery(query);
        jTable1.setModel(util.buildTableModel(rs));

        jTable1.removeColumn(jTable1.getColumnModel().getColumn(0));
    }

    private void setButtonStatus(boolean bBaru, boolean bBatal, boolean bSimpan) {
        btnBaru.setEnabled(bBaru);
        btnBatal.setEnabled(bBatal);
        btnSimpan.setEnabled(bSimpan);
        cmbKategori.setEnabled(bSimpan);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtKode = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSKS = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSemester = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cmbKategori = new javax.swing.JComboBox();
        btnBaru = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setTitle("Form Matakuliah");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Kode");

        jLabel2.setText("Nama");

        jLabel3.setText("SKS");

        jLabel4.setText("Semester");

        jLabel5.setText("Kategori");

        cmbKategori.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TEORI", "PRAKTIKUM" }));

        btnBaru.setText("Data Baru");
        btnBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBaruActionPerformed(evt);
            }
        });

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(btnBaru)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 255, Short.MAX_VALUE)
                        .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtKode, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSKS, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSemester, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSKS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBaru)
                    .addComponent(btnSimpan)
                    .addComponent(btnBatal))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBaruActionPerformed
        // TODO add your handling code here:
        txtKode.setText("");
        txtNama.setText("");
        txtSKS.setText("");
        txtSemester.setText("");

        setButtonStatus(false, true, true);
        _selectedkode = -1;
    }//GEN-LAST:event_btnBaruActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed

        if (("".equals(txtKode.getText().trim()) || "".equals(txtNama.getText().trim()))
                || "".equals(txtSKS.getText().trim()) || "".equals(txtSemester.getText().trim())) {
            JOptionPane.showMessageDialog(null, "Data Belum Lengkap");
            return;
        }

        if (_selectedkode != -1) {
            //update data
            String check = String.format(
                    "SELECT CAST(COUNT(*) AS CHAR(1)) "
                    + "FROM mata_kuliah "
                    + "WHERE (kode_mk= '%s' OR nama= '%s') AND kode <> %d",
                    txtKode.getText(), txtNama.getText(), _selectedkode);
            try {
                int i = Integer.parseInt(MysqlConnect.getDbCon().ExecuteScalar(check));

                if (i != 0) {
                    JOptionPane.showMessageDialog(null, "Kode Atau Nama ini sudah ada!");
                    return;
                }

                String Qry_update = String.format(
                        "UPDATE mata_kuliah "
                        + "set kode_mk = '%s', "
                        + "    nama = '%s', "
                        + "    sks = %d, "
                        + "    semester = %d,"
                        + "    aktif ='%s',"
                        + "    jenis = '%s' "
                        + "where kode = %d",
                        txtKode.getText(),
                        txtNama.getText(),
                        Integer.parseInt(txtSKS.getText()),
                        Integer.parseInt(txtSemester.getText()),
                        "True",
                        cmbKategori.getSelectedItem().toString(),
                        _selectedkode
                );
                MysqlConnect.getDbCon().insert(Qry_update);

            } catch (SQLException ex) {
                Logger.getLogger(FrmPengampu.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            //new data
            String check = String.format(
                    "SELECT CAST(COUNT(*) AS CHAR(1)) "
                    + "FROM mata_kuliah "
                    + "WHERE (kode_mk= '%s' OR nama= '%s')",
                    txtKode.getText(), txtNama.getText());

            try {
                int i = Integer.parseInt(MysqlConnect.getDbCon().ExecuteScalar(check));

                if (i != 0) {
                    JOptionPane.showMessageDialog(null, "Kode Atau Nama ini sudah ada!");
                    return;
                }

                String Qry_insert = String.format(
                        "INSERT INTO mata_kuliah(kode_mk,nama,sks,semester,aktif,jenis) VALUES('%s','%s',%d,%d,'%s','%s')",
                        txtKode.getText(), txtNama.getText(), Integer.parseInt(txtSKS.getText()), Integer.parseInt(txtSemester.getText()), "True", cmbKategori.getSelectedItem().toString());
                MysqlConnect.getDbCon().insert(Qry_insert);

            } catch (SQLException ex) {
                Logger.getLogger(FrmPengampu.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

        _selectedkode = -1; //set to "-1" agar disign sebagai databaru
        txtKode.setText("");
        txtNama.setText("");
        txtSKS.setText("");
        txtSemester.setText("");

        setButtonStatus(true, false, false);

        try {
            loadData();
        } catch (SQLException ex) {
            Logger.getLogger(FrmPengampu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        setButtonStatus(true, false, false);
        txtKode.setText("");
        txtNama.setText("");
        txtSKS.setText("");
        txtSemester.setText("");
    }//GEN-LAST:event_btnBatalActionPerformed

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        int row = jTable1.getSelectedRow();

        setButtonStatus(false, true, true);
        _selectedkode = Integer.parseInt(jTable1.getModel().getValueAt(row, 0).toString());

        txtKode.setText(jTable1.getModel().getValueAt(row, 1).toString());
        txtNama.setText(jTable1.getModel().getValueAt(row, 2).toString());
        txtSKS.setText(jTable1.getModel().getValueAt(row, 3).toString());
        txtSemester.setText(jTable1.getModel().getValueAt(row, 4).toString());
        cmbKategori.setSelectedItem(jTable1.getModel().getValueAt(row, 5).toString());
    }//GEN-LAST:event_jTable1MousePressed

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
         if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_DELETE) {

            if (JOptionPane.showConfirmDialog(null, "Yakin ingin menghapus data ini?",
                    "Konfirmasi",
                    JOptionPane.YES_NO_OPTION) != JOptionPane.YES_OPTION) {
                return;
            }

            int row = jTable1.getSelectedRow();
            _selectedkode = Integer.parseInt(jTable1.getModel().getValueAt(row, 0).toString());

            String Qry_Delete = "DELETE FROM mata_kuliah where kode =  " + _selectedkode;
            try {
                MysqlConnect.getDbCon().ExecuteNonQuery(Qry_Delete);
            } catch (SQLException ex) {
                Logger.getLogger(FrmPengampu.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            Qry_Delete = "DELETE FROM pengampu where kode_mk =  " + _selectedkode;
            try {
                MysqlConnect.getDbCon().ExecuteNonQuery(Qry_Delete);
            } catch (SQLException ex) {
                Logger.getLogger(FrmPengampu.class.getName()).log(Level.SEVERE, null, ex);
            }

            _selectedkode = -1;
            setButtonStatus(true, false, false);
            try {
                loadData();
            } catch (SQLException ex) {
                Logger.getLogger(FrmPengampu.class.getName()).log(Level.SEVERE, null, ex);
            }
        } 
    }//GEN-LAST:event_jTable1KeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBaru;
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox cmbKategori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtKode;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtSKS;
    private javax.swing.JTextField txtSemester;
    // End of variables declaration//GEN-END:variables
}
