/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.geneticAlgorithm.GUI;

import com.geneticAlgorithm.database.MysqlConnect;
import com.geneticAlgorithm.util.util;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author trias
 */
public class FrmRuang extends javax.swing.JInternalFrame {

    private int _selectedkode;

    /**
     * Creates new form FrmRuang
     */
    public FrmRuang() {
        initComponents();
        setButtonStatus(true, false, false);
        try {
            loadData();
        } catch (SQLException ex) {
            Logger.getLogger(FrmDosen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadData() throws SQLException {
        String query
                = "SELECT * FROM ruang";
        ResultSet rs = MysqlConnect.getDbCon().ExecuteQuery(query);
        jTable1.setModel(util.buildTableModel(rs));
        jTable1.removeColumn(jTable1.getColumnModel().getColumn(0));
    }

    private void setButtonStatus(boolean bBaru, boolean bBatal, boolean bSimpan) {
        btnBaru.setEnabled(bBaru);
        btnBatal.setEnabled(bBatal);
        btnSimpan.setEnabled(bSimpan);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtKapasitas = new javax.swing.JTextField();
        cmbJenis = new javax.swing.JComboBox();
        btnBaru = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setTitle("Form Ruang");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Nama");

        jLabel2.setText("Kapasitas");

        jLabel3.setText("Jenis");

        cmbJenis.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TEORI", "LABORATORIUM" }));

        btnBaru.setText("Data Baru");
        btnBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBaruActionPerformed(evt);
            }
        });

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnBaru)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtKapasitas, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cmbJenis, javax.swing.GroupLayout.Alignment.LEADING, 0, 140, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtKapasitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbJenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBaru)
                    .addComponent(btnBatal)
                    .addComponent(btnSimpan))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBaruActionPerformed

        txtNama.setText("");
        txtKapasitas.setText("");
        setButtonStatus(false, true, true);
        _selectedkode = -1;
    }//GEN-LAST:event_btnBaruActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed

        if ("".equals(txtNama.getText().trim()) || "".equals(txtKapasitas.getText().trim())) {
            JOptionPane.showMessageDialog(null, "Data Belum Lengkap");
            return;
        }

        if (_selectedkode != -1) {
            //update data
            String check = String.format(
                    "SELECT CAST(COUNT(*) AS CHAR(1)) "
                    + "FROM ruang "
                    + "WHERE nama= '%s' AND kode <> %d",
                    txtNama.getText(), _selectedkode);
            try {
                int i = Integer.parseInt(MysqlConnect.getDbCon().ExecuteScalar(check));

                if (i != 0) {
                    JOptionPane.showMessageDialog(null, "Nama ini sudah ada!");
                    return;
                }

                String Qry_update = String.format(
                        "UPDATE ruang "
                        + "set nama = '%s', "
                        + "    kapasitas = %d, "
                        + "    jenis = '%s' "
                        + "where kode = %d",
                        txtNama.getText(),
                        Integer.parseInt(txtKapasitas.getText()),
                        cmbJenis.getSelectedItem().toString(),
                        _selectedkode
                );
                MysqlConnect.getDbCon().insert(Qry_update);

            } catch (SQLException ex) {
                Logger.getLogger(FrmPengampu.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            //new data
            String check = String.format(
                    "SELECT CAST(COUNT(*) AS CHAR(1)) "
                    + "FROM ruang "
                    + "WHERE nama= '%s'",
                    txtNama.getText());

            try {
                int i = Integer.parseInt(MysqlConnect.getDbCon().ExecuteScalar(check));

                if (i != 0) {
                    JOptionPane.showMessageDialog(null, "Nama ini sudah ada!");
                    return;
                }

                String Qry_insert = String.format(
                        "INSERT INTO ruang(nama,kapasitas,jenis) VALUES('%s',%d,'%s')",
                        txtNama.getText(), Integer.parseInt(txtKapasitas.getText()),
                        cmbJenis.getSelectedItem().toString());
                MysqlConnect.getDbCon().insert(Qry_insert);

            } catch (SQLException ex) {
                Logger.getLogger(FrmPengampu.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

        _selectedkode = -1; //set to "-1" agar disign sebagai databaru

        txtNama.setText("");
        txtKapasitas.setText("");
        setButtonStatus(true, false, false);

        try {
            loadData();
        } catch (SQLException ex) {
            Logger.getLogger(FrmPengampu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        setButtonStatus(true, false, false);
        txtNama.setText("");
        txtKapasitas.setText("");
    }//GEN-LAST:event_btnBatalActionPerformed

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        int row = jTable1.getSelectedRow();

        setButtonStatus(false, true, true);
        _selectedkode = Integer.parseInt(jTable1.getModel().getValueAt(row, 0).toString());

        txtNama.setText(jTable1.getModel().getValueAt(row, 1).toString());
        txtKapasitas.setText(jTable1.getModel().getValueAt(row, 2).toString());
        cmbJenis.setSelectedItem(jTable1.getModel().getValueAt(row, 3).toString());
    }//GEN-LAST:event_jTable1MousePressed

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_DELETE) {

            if (JOptionPane.showConfirmDialog(null, "Yakin ingin menghapus data ini?",
                    "Konfirmasi",
                    JOptionPane.YES_NO_OPTION) != JOptionPane.YES_OPTION) {
                return;
            }

            int row = jTable1.getSelectedRow();
            _selectedkode = Integer.parseInt(jTable1.getModel().getValueAt(row, 0).toString());

            String Qry_Delete = "DELETE FROM ruang where kode =  " + _selectedkode;
            try {
                MysqlConnect.getDbCon().ExecuteNonQuery(Qry_Delete);
            } catch (SQLException ex) {
                Logger.getLogger(FrmPengampu.class.getName()).log(Level.SEVERE, null, ex);
            }

            _selectedkode = -1;
            setButtonStatus(true, false, false);
            try {
                loadData();
            } catch (SQLException ex) {
                Logger.getLogger(FrmPengampu.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jTable1KeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBaru;
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox cmbJenis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtKapasitas;
    private javax.swing.JTextField txtNama;
    // End of variables declaration//GEN-END:variables
}
